'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stations=[
 {id:'words',name:'Wortarten-Labor',icon:'🔬',x:220,y:180,rule:'Nomen benennen Dinge, Lebewesen und Vorstellungen. Verben beschreiben Tätigkeiten, Vorgänge und Zustände. Adjektive beschreiben Eigenschaften. Artikel begleiten Nomen, Pronomen vertreten oder begleiten sie. Adverbien wie gestern und dort sind unveränderlich.'},
 {id:'cases',name:'Vier-Fälle-Burg',icon:'🏰',x:550,y:130,rule:'Nominativ: Wer oder was? Genitiv: Wessen? Dativ: Wem? Akkusativ: Wen oder was? Frage nach der markierten Wortgruppe im ganzen Satz.'},
 {id:'subject',name:'Subjekt-Wald',icon:'🌳',x:875,y:185,rule:'Frage: Wer oder was + Prädikat? Das vollständige Subjekt umfasst auch Artikel und Adjektive: Der kleine Hund. Es steht nicht immer am Satzanfang.'},
 {id:'predicate',name:'Prädikat-Werkstatt',icon:'⚒️',x:200,y:455,rule:'Markiere alle verbalen Teile: räumt … auf; hat … geschlafen; muss … lernen. Bei „Sie ist glücklich“ markierst du wie auf deinem Arbeitsblatt nur „ist“.'},
 {id:'spelling',name:'Wörter-Mine',icon:'💎',x:475,y:535,extra:true,rule:'Verlängern: Hund → Hunde, also d. Ableiten: Bäume → Baum, also äu. das/dass: Kannst du dieses, jenes oder welches einsetzen? Dann das.'},
 {id:'clauses',name:'Satzbau-Hafen',icon:'⛵',x:830,y:475,extra:true,rule:'Nebensätze werden mit Komma abgetrennt. Das finite Verb steht meist am Ende. weil = Grund, obwohl = Gegengrund, wenn = Bedingung, damit = Zweck; bevor und nachdem = Zeit.'},
 {id:'mood',name:'Konjunktiv-Turm',icon:'🗼',x:1000,y:350,extra:true,rule:'Konjunktiv I: Er sagt, er sei müde; sie habe Zeit. Konjunktiv II für Wünsche und Möglichkeiten: Ich wäre gern dort; wenn ich Zeit hätte, würde ich kommen.'}
];
const wisdom={
 general:[
  ['Wer? Wessen? Wem? Wen? So lassen sich die Fälle versteh’n!','Die vier Fragewörter führen der Reihe nach zu Nominativ, Genitiv, Dativ und Akkusativ.'],
  ['Erst den Satz verstehen, dann auf Fragewort-Jagd gehen!','Lies immer den ganzen Satz. Danach hilft dir die passende Frage beim Bestimmen.']
 ],
 words:[
  ['Ist das Nomen gerade nicht da, springt das Pronomen ein – hurra!','Pronomen vertreten oder begleiten ein Nomen: ich, du, er, dieser oder mein.'],
  ['Wie ist das Ding? Das Adjektiv kriegt’s hin!','Adjektive beschreiben Eigenschaften: klein, mutig, hell. Man kann viele davon steigern.'],
  ['Der, die, das marschieren vor und stellen dir das Nomen vor.','Artikel begleiten Nomen. Bestimmte Artikel sind der, die, das; unbestimmte sind ein und eine.'],
  ['Was passiert und was wird gemacht? Das Verb hält jeden Satz auf Trab!','Verben sagen, was jemand tut oder was geschieht: laufen, denken, wachsen.'],
  ['Wann, wo, wie und warum? Das Adverb erklärt’s rundherum!','Adverbien geben Umstände an, zum Beispiel gestern, dort, gern oder deshalb.']
 ],
 cases:[
  ['Wer oder was steht hier herum? Der Nominativ – der macht sich wichtig!','Frage nach dem Nominativ mit „Wer oder was?“. Er ist meist der Täter im Satz.'],
  ['Wessen Keks ist verschwunden? Der Genitiv will den Besitzer erkunden!','Das entscheidende Fragewort ist „Wessen?“. Der Genitiv zeigt oft Zugehörigkeit.'],
  ['Wem gebe ich den Kuchen? Dem Dativ, dem Schlauen!','Das entscheidende Fragewort ist „Wem?“. Oft erkennst du ihn an dem oder einem.'],
  ['Wen oder was frisst der Drache? Der Akkusativ kennt die Sache!','Frage mit „Wen oder was?“. Beim männlichen Nomen steht oft den oder einen.']
 ],
 subject:[
  ['Wer macht den Quatsch? Das Subjekt war’s!','Frage „Wer oder was tut etwas?“. Die ganze Antwort gehört zum Subjekt, etwa „der kleine Hund“.'],
  ['Der Täter ist nicht immer vorn – such Wer oder was, sonst bleibst du verlor’n!','Das Subjekt kann auch in der Mitte oder am Ende eines Satzes stehen.']
 ],
 predicate:[
  ['Was tut das Subjekt? Das Prädikat verrät’s direkt!','Das Prädikat besteht aus einem Verb und sagt, was getan wird oder geschieht.'],
  ['Räumt Paul sein Zimmer auf, passen zwei Verbteile drauf!','Ein Prädikat kann getrennt sein: „räumt … auf“ oder „hat … geschlafen“. Markiere alle Teile.']
 ],
 spelling:[
  ['Mehrzahl machen, Endlaut knacken!','Verlängere ein Wort: Aus Hund wird Hunde. So hörst du das d am Ende.'],
  ['Such die Wortfamilie – sie verrät dir ä und äu!','Leite das Wort ab: Baum gehört zu Bäume. Deshalb schreibt man äu.'],
  ['Dieses, jenes, welches passt? Dann schreibt man das – sonst dass!','Kannst du eines der Ersatzwörter einsetzen, schreibst du „das“. Sonst steht häufig „dass“.']
 ],
 clauses:[
  ['Im Nebensatz, das ist bekannt, steht das Verb meist ganz am Rand!','Bei „weil Paul heute lernt“ steht das gebeugte Verb „lernt“ am Ende.'],
  ['Kommt der Nebensatz herbei, macht das Komma Platz für zwei!','Hauptsatz und Nebensatz werden durch ein Komma voneinander getrennt.']
 ],
 mood:[
  ['Wäre, hätte, könnte – der Konjunktiv erfüllt fast jeden Wunsch!','Der Konjunktiv II beschreibt Wünsche, Möglichkeiten und Dinge, die nicht wirklich sind.'],
  ['Er sagt, er sei: Hörst du fremde Rede dabei?','Der Konjunktiv I wird oft in der indirekten Rede benutzt: „Er sagt, er sei müde.“']
 ]
};
let lastWisdom=-1;
let token='',role='',state=null,busy=false,current=null,currentStation=null,currentLevel=1,selection=[],round={n:0,correct:0,delta:0},miniTimer=null,toastTimer=null;
try{token=sessionStorage.getItem('lern-session')||localStorage.getItem('lern-session')||''}catch{}
const params=new URLSearchParams(location.hash.slice(1));let setupKey=params.get('setup');if(setupKey){history.replaceState(null,'',location.pathname);$('setupPanel').hidden=false;$('loginPanel').hidden=true;token='';}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',4500)}
async function api(action,payload={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);$('cloud').textContent='Wird synchronisiert …';try{const r=await fetch(LERN_CONFIG.url+'/rest/v1/rpc/lern_api',{method:'POST',headers:{'Content-Type':'application/json',apikey:LERN_CONFIG.key},body:JSON.stringify({action,payload,session_token:token}),signal:controller.signal});if(!r.ok)throw Error('Online-Verbindung nicht verfügbar. Bitte erneut versuchen.');const out=await r.json();if(out.error){if(out.auth===false){token='';clearSession();showEntry()}throw Error(out.error)}$('cloud').textContent='✓ Online gespeichert';return out}catch(e){$('cloud').textContent='Verbindung prüfen';throw Error(e.name==='AbortError'?'Zeitüberschreitung. Bitte erneut versuchen; Antworten werden nicht doppelt gebucht.':e.message)}finally{clearTimeout(timeout)}}
function clearSession(){try{sessionStorage.removeItem('lern-session');localStorage.removeItem('lern-session')}catch{}}
function showEntry(){$('entry').hidden=false;$('play').hidden=true;$('parent').hidden=true;$('logout').hidden=true;if($('modal').open)$('modal').close()}
async function refresh(){state=await api('state');role=state.role;renderState();return state}
function totals(){return(state?.stats||[]).reduce((s,x)=>({n:s.n+Number(x.total),c:s.c+Number(x.correct)}),{n:0,c:0})}
function tableHtml(){return '<div class="tablewrap"><table><thead><tr><th>Station</th><th>Leicht</th><th>Mittel</th><th>Schwer</th></tr></thead><tbody>'+stations.map(t=>'<tr><th>'+esc(t.name)+'</th>'+[1,2,3].map(l=>{let s=state.stats.find(x=>x.topic===t.id&&x.level===l);return '<td>'+(s?s.correct+'/'+s.total+' richtig':'–')+'</td>'}).join('')+'</tr>').join('')+'</tbody></table></div>'}
function daysHtml(){return state.days.length?'<div class="tablewrap"><table><thead><tr><th>Tag</th><th>Richtig</th><th>Punkte netto</th><th>Aufgabenzeit*</th></tr></thead><tbody>'+state.days.map(d=>'<tr><td>'+esc(d.day)+'</td><td>'+d.correct+'/'+d.total+'</td><td>'+d.points+'</td><td>'+d.minutes+' Min.</td></tr>').join('')+'</tbody></table></div><p class="small muted">*Zeit zwischen Aufgabenstart und Antwort, auf höchstens 2 Minuten je Antwort begrenzt. Keine Messung konzentrierter Lernzeit.</p>':'<p>Noch keine Antworten gespeichert.</p>'}
function renderState(){const count=totals();$('balance').textContent=state.balance;$('rewardBar').style.width=(state.balance+state.redeemed)/20+'%';$('rewardText').textContent=(state.balance+state.redeemed)+' / 2.000 · davon '+state.redeemed+' eingelöst';$('medals').innerHTML=stations.filter(t=>state.stats.filter(s=>s.topic===t.id&&s.level===3&&s.correct>=7).length).map(t=>'<span class="badge">✦ '+esc(t.name)+'</span>').join('');$('stationList').innerHTML=stations.map((t,i)=>{const ss=state.stats.filter(s=>s.topic===t.id),n=ss.reduce((sum,s)=>sum+Number(s.correct),0);return '<button class="stationbutton" data-station="'+i+'"><span>'+t.icon+'</span><span><b>'+t.name+'</b><small>'+n+' richtige Antworten'+(t.extra?' · Ergänzung':'')+'</small></span></button>'}).join('');document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>travel(Number(b.dataset.station)));$('newSage').onclick=()=>showWisdom(currentStation?.id||'general');showWisdom('general');$('parentStats').innerHTML='<div class="card metrics"><p><b>'+state.balance+'</b>verfügbar</p><p><b>'+state.redeemed+'</b>bereits eingelöst</p><p><b>'+count.c+'/'+count.n+'</b>richtig beantwortet</p></div><div class="card"><h2>Lernstand je Schwierigkeitsstufe</h2>'+tableHtml()+'</div><div class="card"><h2>Die letzten Lerntage</h2>'+daysHtml()+'</div>';$('amount').max=state.balance;$('redemptions').innerHTML=state.redemptions.length?state.redemptions.map(r=>'<p>'+r.amount+' Punkte · '+new Date(r.at).toLocaleString('de-DE')+'</p>').join(''):'Noch keine Einlösungen.'}
async function enter(){await refresh();$('entry').hidden=true;$('play').hidden=role!=='paul';$('parent').hidden=role!=='eltern';$('logout').hidden=false;if(role==='paul')$('world').focus()}
$('loginForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const btn=e.submitter;btn.disabled=true;$('entryMessage').textContent='Anmeldung läuft …';try{const out=await api('login',{name:$('name').value,password:$('password').value});token=out.token;clearSession();try{($('remember').checked?localStorage:sessionStorage).setItem('lern-session',token)}catch{}$('password').value='';await enter();$('entryMessage').textContent=''}catch(e){$('entryMessage').textContent=e.message}finally{busy=false;btn.disabled=false}};
$('setupForm').onsubmit=async e=>{e.preventDefault();if(busy)return;if($('parentPass').value!==$('parentRepeat').value){$('entryMessage').textContent='Die Elternpasswörter stimmen nicht überein.';return}busy=true;e.submitter.disabled=true;try{await api('setup',{key:setupKey,paul_password:$('paulPass').value,parent_password:$('parentPass').value});$('setupForm').reset();setupKey=null;$('setupPanel').hidden=true;$('loginPanel').hidden=false;$('entryMessage').textContent='Zugänge eingerichtet! Paul und Eltern können sich jetzt anmelden.'}catch(err){$('entryMessage').textContent=err.message}finally{busy=false;e.submitter.disabled=false}};
$('logout').onclick=async()=>{if(busy)return;try{await api('logout');clearSession();token='';state=null;showEntry()}catch(e){toast(e.message)}};
let redemptionId=null;$('redeemForm').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;e.submitter.disabled=true;redemptionId||=crypto.randomUUID();try{await api('redeem',{amount:Number($('amount').value),request_id:redemptionId});redemptionId=null;$('redeemForm').reset();await refresh();$('redeemMessage').textContent='Einlösung gespeichert.'}catch(err){$('redeemMessage').textContent=err.message}finally{busy=false;e.submitter.disabled=false}};
function modal(label,html){clearInterval(miniTimer);keys.clear();destination=null;$('modalLabel').textContent=label;$('modalContent').innerHTML=html;$('modalError').textContent='';if(!$('modal').open)$('modal').showModal()}
function pickWisdom(topic='general'){const list=wisdom[topic]||wisdom.general;lastWisdom=(lastWisdom+1)%list.length;return list[lastWisdom]}
function showWisdom(topic='general'){const [quote,explain]=pickWisdom(topic);if($('sageQuote'))$('sageQuote').textContent='„'+quote+'“';if($('sageExplain'))$('sageExplain').innerHTML='<strong>Das ist gemeint:</strong> '+esc(explain)}
function wisdomHtml(topic){const [quote,explain]=pickWisdom(topic);return '<div class="sage-mini"><img src="merkmeister.png" alt="Der Merkmeister"><div><blockquote>„'+esc(quote)+'“</blockquote><p><strong>Das ist gemeint:</strong> '+esc(explain)+'</p></div></div>'}
$('closeModal').onclick=()=>{if(!busy)$('modal').close()};$('modal').addEventListener('cancel',e=>{if(busy)e.preventDefault()});$('modal').addEventListener('close',()=>{clearInterval(miniTimer);keys.clear();$('world').focus()});
function stationOpen(t){currentStation=t;showWisdom(t.id);modal(t.icon+' '+t.name,'<h2>Wähle deine Herausforderung.</h2>'+wisdomHtml(t.id)+'<p>Richtig bringt Punkte. Falsch kostet 1 Punkt, aber dein Konto fällt nie unter 0.</p><div class="levels">'+[1,2,3].map((l,i)=>'<button class="level" data-level="'+l+'"><span>'+['🌱 Leicht','🔥 Mittel','⚡ Schwer'][i]+'</span><strong>+'+[1,3,6][i]+'</strong><small>'+['Mit Merkhilfe und Auswahl','Wörter markieren und selbst ergänzen','Antworten ohne Auswahl formulieren'][i]+'</small></button>').join('')+'</div><details><summary>Merkwissen vor der Runde</summary><p class="tip">'+t.rule+'</p></details>'+(t.extra?'<p class="small muted">Vorläufige Ergänzung bis die Arbeitsheftseiten vorliegen.</p>':''));document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{currentLevel=Number(b.dataset.level);miniGame()})}
function miniGame(){let hits=0,seconds=15;modal('Kurzes Aufwärmen','<h2>Triff drei Zielscheiben!</h2><p>Ein Klick pro Ziel. Keine Lernpunkte, kein Punktabzug.</p><div class="targetgame"><button id="target" aria-label="Zielscheibe treffen" style="left:15%;top:25%">🎯</button></div><p id="miniStatus" class="small">0 / 3 Treffer · 15 Sekunden</p><button class="primary full" id="skipMini">Direkt zur Deutsch-Challenge</button>');const go=()=>{clearInterval(miniTimer);round={n:0,correct:0,delta:0};nextQuestion()};$('skipMini').onclick=go;$('target').onclick=()=>{hits++;if(hits>=3){go();return}$('target').style.left=(10+Math.random()*65)+'%';$('target').style.top=(10+Math.random()*55)+'%';$('miniStatus').textContent=hits+' / 3 Treffer · '+seconds+' Sekunden'};miniTimer=setInterval(()=>{seconds--;if(seconds<=0){go();return}if($('miniStatus'))$('miniStatus').textContent=hits+' / 3 Treffer · '+seconds+' Sekunden'},1000)}
async function nextQuestion(){if(busy)return;busy=true;modal(currentStation.name,'<h2>Deine nächste Aufgabe wird geladen …</h2>');try{const q=await api('next',{topic:currentStation.id,level:currentLevel});if(q.cooldown){modal('Gut geübt!','<h2>Hier ist eine Lernpause dran.</h2><p>'+esc(q.message)+'</p>');await refresh();return}current=q;currentStation=stations.find(t=>t.id===q.topic);currentLevel=q.level;renderQuestion()}catch(e){modal('Verbindung prüfen','<h2>Aufgabe noch nicht geladen.</h2><p>'+esc(e.message)+'</p><button id="loadAgain">Erneut versuchen</button>');$('loadAgain').onclick=nextQuestion}finally{busy=false}}
function safeText(s){return esc(s).replaceAll('&lt;mark&gt;','<mark>').replaceAll('&lt;/mark&gt;','</mark>')}
function renderQuestion(){selection=[];const t=current.task;let html='<div class="small muted">'+['Leicht · +1','Mittel · +3','Schwer · +6'][currentLevel-1]+' bei richtig · −1 bei falsch · Runde '+(round.n+1)+'/10</div><h2>'+esc(t.title)+'</h2>'+wisdomHtml(currentStation.id)+(t.hint?'<div class="tip">'+esc(t.hint)+'</div>':'')+'<div class="question">'+safeText(t.text)+'</div>';
if(t.kind==='mc')html+='<div class="answers">'+shuffle(t.options).map(v=>'<button class="answerOption">'+esc(v)+'</button>').join('')+'</div>';
if(t.kind==='input')html+='<form id="answerForm"><label for="freeAnswer">Deine Antwort'+(current.topic==='spelling'?' – Groß- und Kleinschreibung zählt':'')+'</label><input id="freeAnswer" autocomplete="off" spellcheck="false" autocorrect="off" required><button class="primary full" style="margin-top:14px">Antwort prüfen</button></form>';
if(t.kind==='mark')html+='<p class="small muted">Wähle alle passenden Wörter aus.</p><div class="tokens">'+t.text.split(' ').map((w,i)=>'<button data-word="'+i+'" aria-pressed="false">'+esc(w)+'</button>').join('')+'</div><button id="checkWords" class="primary" disabled>Auswahl prüfen</button>';
if(t.kind==='order')html+='<div class="buildzone"><div id="built" class="tokens"></div></div><div id="bank" class="tokens"></div><button id="checkOrder" class="primary" disabled>Satz prüfen</button>';
html+='<div id="answerResult" role="status"></div>';modal(currentStation.icon+' '+currentStation.name,html);
document.querySelectorAll('.answerOption').forEach(b=>b.onclick=()=>submitAnswer(b.textContent));if(t.kind==='input')$('answerForm').onsubmit=e=>{e.preventDefault();submitAnswer($('freeAnswer').value.trim())};document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.word);selection=selection.includes(i)?selection.filter(x=>x!==i):[...selection,i];b.setAttribute('aria-pressed',selection.includes(i));$('checkWords').disabled=!selection.length});if(t.kind==='mark')$('checkWords').onclick=()=>submitAnswer([...selection].sort((a,b)=>a-b).map(i=>t.text.split(' ')[i]).join(' '));if(t.kind==='order'){current.bank=shuffle(t.chunks.map((_,i)=>i));drawOrder();$('checkOrder').onclick=()=>submitAnswer(selection.map(i=>t.chunks[i]).join(' '))}}
function drawOrder(){const chunks=current.task.chunks;$('built').innerHTML=selection.map(i=>'<button data-remove="'+i+'">'+esc(chunks[i])+'</button>').join('');$('bank').innerHTML=current.bank.filter(i=>!selection.includes(i)).map(i=>'<button data-add="'+i+'">'+esc(chunks[i])+'</button>').join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{selection.push(Number(b.dataset.add));drawOrder()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{selection=selection.filter(i=>i!==Number(b.dataset.remove));drawOrder()});$('checkOrder').disabled=selection.length!==chunks.length}
async function submitAnswer(value){if(busy||!value)return;busy=true;const controls=[...$('modalContent').querySelectorAll('button,input')];controls.forEach(b=>b.disabled=true);$('modalError').textContent='';try{const r=await api('answer',{attempt:current.attempt,answer:value});round.n++;round.correct+=Number(r.correct);round.delta+=r.delta;$('answerResult').className='result'+(r.correct?'':' wrong');$('answerResult').innerHTML='<h3>'+(r.correct?'Treffer! ':'Noch nicht ganz. ')+(r.delta>0?'+':'')+r.delta+' '+(Math.abs(r.delta)===1?'Punkt':'Punkte')+'</h3><p><strong>Lösung: '+esc(r.answer)+'</strong></p><p>'+esc(r.why)+'</p>'+(r.capped?'<p>Deine Belohnungsgrenze ist erreicht. Du kannst weiter üben.</p>':'')+'<div class="row"><button class="primary" id="nextQuestion">'+(round.n>=10?'Runde auswerten':'Nächste Aufgabe →')+'</button><button id="backIsland">Zur Insel</button></div>';$('nextQuestion').onclick=round.n>=10?roundEnd:nextQuestion;$('backIsland').onclick=()=>$('modal').close();$('nextQuestion').focus();try{await refresh()}catch(e){toast('Antwort gespeichert. Übersicht aktualisiert sich beim nächsten Laden.')}}catch(e){$('modalError').textContent=e.message;controls.forEach(b=>b.disabled=false)}finally{busy=false}}
function roundEnd(){modal('Runde beendet','<h2>'+round.correct+' von '+round.n+' richtig.</h2><div class="metrics"><p><b>'+(round.delta>0?'+':'')+round.delta+'</b>Punkte in dieser Runde</p><p><b>'+state.balance+'</b>auf deinem Konto</p></div><p class="tip">'+(round.correct>=8?'Starke Runde. Du kannst die nächste Stufe ausprobieren!':'Lies das Merkwissen und probiere es beim nächsten Mal wieder. Fehler gehören zum Lernen.')+'</p><button class="primary" id="chooseAgain">Schwierigkeit wählen</button>');$('chooseAgain').onclick=()=>stationOpen(currentStation)}
$('journalBtn').onclick=()=>modal('Dein Lerntagebuch','<h2>Das hast du schon geschafft.</h2>'+tableHtml()+'<h3 style="margin-top:20px">Deine Lerntage</h3>'+daysHtml()+'<div class="tip">Leicht +1, mittel +3, schwer +6. Falsch −1, mindestens 0. Eine Grundaufgabe wird alle 12 Stunden erneut gewertet. Jede schwere Stufe mit 7 richtigen Antworten erhält ein Abzeichen.</div>');
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
// The canvas is the actual playable world: positions, paths and hit areas share coordinates.
const canvas=$('world'),g=canvas.getContext('2d'),player={x:550,y:340},keys=new Set();let destination=null,near=null,last=0,walk=0;
function travel(i){currentStation=stations[i];showWisdom(currentStation.id);destination={x:currentStation.x,y:currentStation.y+65};canvas.focus();toast('Unterwegs zu '+currentStation.name)}
function roundRect(x,y,w,h,r,fill,stroke){g.beginPath();g.roundRect(x,y,w,h,r);if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.lineWidth=2;g.stroke()}}
function draw(time){g.clearRect(0,0,1100,700);g.fillStyle='#78becd';g.fillRect(0,0,1100,700);g.strokeStyle='#b8e4e550';g.lineWidth=3;for(let y=35;y<700;y+=70)for(let x=10;x<1100;x+=110){g.beginPath();g.arc(x+Math.sin(time/3000+y)*6,y,16,.1,2.8);g.stroke()}roundRect(55,65,990,580,150,'#e7d6a0');roundRect(76,78,950,547,140,'#8dbd75');g.fillStyle='#7bad65';for(let i=0;i<90;i++){let x=125+(i*137)%840,y=120+(i*79)%450;g.fillRect(x,y,3,7);g.fillRect(x+5,y+2,3,5)}
g.lineCap='round';g.lineJoin='round';g.strokeStyle='#dace9c';g.lineWidth=32;stations.forEach(t=>{g.beginPath();g.moveTo(550,340);g.lineTo(t.x,t.y+55);g.stroke()});g.strokeStyle='#e6dcb1';g.lineWidth=22;stations.forEach(t=>{g.beginPath();g.moveTo(550,340);g.lineTo(t.x,t.y+55);g.stroke()});
g.textAlign='center';g.textBaseline='middle';g.font='38px Segoe UI Emoji';[[100,170],[120,290],[335,115],[750,110],[950,100],[960,585],[635,580],[335,595],[85,530]].forEach(([x,y],i)=>g.fillText(i%3?'🌲':'🪨',x,y));
stations.forEach(t=>{const active=near===t;g.fillStyle=active?'#fff8d766':'#244d2d20';g.beginPath();g.ellipse(t.x,t.y+27,63,24,0,0,Math.PI*2);g.fill();if(active){g.strokeStyle='#fff5ae';g.lineWidth=4;g.beginPath();g.ellipse(t.x,t.y+30,67,30,0,0,Math.PI*2);g.stroke()}g.fillStyle='#ffffff';g.font='60px Segoe UI Emoji';g.fillText(t.icon,t.x,t.y-5);g.font='bold 16px system-ui';const width=g.measureText(t.name).width+22;roundRect(t.x-width/2,t.y+40,width,31,8,'#fffef0','#6d9466');g.fillStyle='#244335';g.fillText(t.name,t.x,t.y+56)});
g.fillStyle='#ffffff';g.font='40px Segoe UI Emoji';g.fillText('🏕️',540,296);g.font='bold 15px system-ui';g.fillStyle='#345638';g.fillText('BASISLAGER',540,268);g.fillStyle='#1d382b35';g.beginPath();g.ellipse(player.x,player.y+17,18,7,0,0,Math.PI*2);g.fill();g.fillStyle='#ffffff';g.font='40px Segoe UI Emoji';g.fillText('🧑‍🚀',player.x,player.y+Math.sin(walk)*2);g.font='bold 13px system-ui';roundRect(player.x-23,player.y-42,46,20,7,'#183848');g.fillStyle='white';g.fillText('PAUL',player.x,player.y-32);
g.fillStyle='#214858';g.font='bold 16px system-ui';g.fillText('N',1030,38);g.font='25px system-ui';g.fillText('↑',1030,62);}
function frame(t){let dt=Math.min((t-last)/1000||0,.05);last=t;if(!$('play').hidden&&!$('modal').open){let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;if(dx||dy)destination=null;else if(destination){dx=destination.x-player.x;dy=destination.y-player.y;if(Math.hypot(dx,dy)<5){destination=null;dx=dy=0}}let norm=Math.hypot(dx,dy);if(norm){player.x=Math.max(100,Math.min(1030,player.x+dx/norm*180*dt));player.y=Math.max(100,Math.min(610,player.y+dy/norm*180*dt));walk+=dt*15}near=stations.find(s=>Math.hypot(s.x-player.x,s.y+55-player.y)<82)||null;$('enterStation').disabled=!near;$('enterStation').textContent=near?'E · '+near.name:'Station betreten';$('location').textContent=near?near.name+' · E zum Öffnen':'Basislager · Lauf zu einer Station';draw(t)}requestAnimationFrame(frame)}requestAnimationFrame(frame);
window.addEventListener('keydown',e=>{if($('play').hidden||$('modal').open||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e'].includes(k)){e.preventDefault();keys.add(k);if(k==='e'&&near&&!e.repeat)stationOpen(near)}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{keys.clear();destination=null});$('enterStation').onclick=()=>{if(near)stationOpen(near)};
canvas.addEventListener('pointerdown',e=>{const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)/rect.width*1100,y=(e.clientY-rect.top)/rect.height*700;const s=stations.find(t=>Math.hypot(t.x-x,t.y+20-y)<75);if(s)destination={x:s.x,y:s.y+65};else destination={x:Math.max(100,Math.min(1030,x)),y:Math.max(100,Math.min(610,y))};canvas.focus()});
document.querySelectorAll('[data-move]').forEach(b=>{let key={up:'w',down:'s',left:'a',right:'d'}[b.dataset.move];b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(key)});['pointerup','pointercancel','lostpointercapture'].forEach(ev=>b.addEventListener(ev,()=>keys.delete(key)))});
if(token&&!setupKey)enter().catch(e=>{$('entryMessage').textContent=e.message;showEntry()});

